// Copyright (C) 2023-2026 Atsora Solutions
//
// SPDX-License-Identifier: Apache-2.0
//
// "Bridge" theming for compile-once. Generates, from the base palette in
// dark/light.less:
//   themes/theme-colors.less : CSS custom properties (:root = light, html.dark =
//                              dark), section-organised, base colors + precomputed
//                              lighten/darken/fade variants. Loaded ONCE, globally.
//   themes/theme.less        : the BRIDGE — @color_x: var(--color_x); for every
//                              color + variant, then @import "common.less". Injected
//                              at compile so the ~326 source files keep writing
//                              @color_x but compile to var(--color_x). ONE compile.
// Also writes theme-color-vars.json (variant list) for the function codemod.
//
// The three outputs (theme.less, theme-colors.less, theme-color-vars.json) are
// GENERATED artifacts (gitignored) — regenerated by the build, never committed.
// Run from anywhere: `node libraries/build-theme.mjs` (paths are repo-relative).

import { execSync } from 'node:child_process'
import { writeFileSync, rmSync, readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..') // pomamo-web-components root
const libAbs = resolve(ROOT, 'libraries')
const themes = resolve(libAbs, 'themes')
const read = f => readFileSync(resolve(themes, f), 'utf8')
const darkSrc = read('dark.less')

// Base palette = dark.less @-vars BEFORE the abandoned :root WIP block.
const preRoot = darkSrc.slice(0, darkSrc.search(/^\s*:root\s*\{/m))
const baseVars = [...new Set([...preRoot.matchAll(/^\s*@([A-Za-z_]\w*)\s*:/gm)].map(m => m[1]))]

const variants = [
  ['color_highlight', 'lighten', 15], ['box_color', 'darken', 10], ['input_background_color', 'darken', 10],
  ['color_background_alternate', 'lighten', 15], ['color_window_alternate', 'darken', 10],
  ['color_window', 'lighten', 15], ['box_color', 'lighten', 10], ['color_window', 'darken', 5],
  ['color_window', 'lighten', 4], ['color_background_alternate', 'lighten', 10], ['color_window', 'darken', 4],
  ['input_background_color', 'lighten', 10], ['color_window_border', 'lighten', 15], ['color_window', 'lighten', 5],
  ['color_background_alternate', 'lighten', 35], ['color_background', 'lighten', 10], ['color_white', 'darken', 10],
  ['color_background', 'darken', 10],
  ['color_text', 'fade', 90], ['color_red', 'fade', 70], ['color_highlight', 'fade', 5],
  ['color_highlight', 'fade', 2], ['color_purple', 'fade', 50],
]

function compute(theme) {
  // Define the variants up-front (LESS resolves them lazily once the theme is
  // imported) so common.less — which now references e.g. @color_purple_fade50 —
  // still compiles standalone for value extraction.
  const variantDefs = variants.map(([v, fn, n]) => `@${v}_${fn}${n}: ${fn}(@${v}, ${n}%);`).join('\n')
  const body = `${baseVars.map(v => `  --${v}: @${v};`).join('\n')}\n${variants.map(([v, fn, n]) => `  --${v}_${fn}${n}: @${v}_${fn}${n};`).join('\n')}`
  const gen = resolve(libAbs, '_gen.less')
  writeFileSync(gen, `${variantDefs}\n@import "themes/${theme}.less";\n.x{\n${body}\n}\n`)
  const css = execSync(`"${resolve(ROOT, 'node_modules/.bin/lessc')}" --include-path="${libAbs}" "${gen}"`, { encoding: 'utf8' })
  rmSync(gen)
  const map = {}
  for (const m of css.matchAll(/--([\w]+):\s*([^;]+);/g)) map[m[1]] = m[2].trim()
  return map
}
const L = compute('light')
const D = compute('dark')

const isColor = v => /^(#[0-9a-f]{3,8}|rgba?\(|hsla?\()/i.test(v || '')
const forceCss = new Set(['box_shadow', 'background_image', 'product_logo', 'customer_logo'])
const isCss = n => forceCss.has(n) || isColor(L[n]) || isColor(D[n])
const colorVars = baseVars.filter(isCss)

// theme-colors.less : section-organised, walking dark.less pre-:root, colors only.
function colorBlock(vals, sel) {
  const lines = ['']
  let started = false
  for (const line of preRoot.split('\n')) {
    if (!started) { if (/MAIN COLORS/.test(line)) started = true; else continue }
    // Asterisk-box section header "* NAME *" -> clean single-line /* NAME */.
    const sec = line.match(/^\s*\*\s+([A-Za-z][\w &-]*[A-Za-z])\s+\*\s*$/)
    if (sec) { lines.push(`  /* ${sec[1].trim()} */`); continue }
    if (/^\s*\/?\*{2,}\/?\s*$/.test(line)) continue // asterisk border lines
    const m = line.match(/^(\s*)@([A-Za-z_]\w*)\s*:\s*[^;]+;(.*)$/)
    if (m) { if (isCss(m[2])) lines.push(`  ${m[1]}--${m[2]}: ${vals[m[2]]};${m[3]}`); continue }
    if (/^\s*@import|^\s*;/.test(line)) continue
    lines.push(line ? `  ${line}` : '')
  }
  lines.push('\n  /* DERIVED VARIANTS (precomputed) */')
  for (const [v, fn, n] of variants) lines.push(`  --${v}_${fn}${n}: ${vals[`${v}_${fn}${n}`]};`)
  return `${sel} {${lines.join('\n').replace(/\n{3,}/g, '\n\n')}\n}\n`
}

const hdr = t => `// Copyright (C) 2023-2026 Atsora Solutions\n//\n// SPDX-License-Identifier: Apache-2.0\n//\n// GENERATED by libraries/build-theme.mjs — do not edit, do not commit.\n// ${t}\n\n`
writeFileSync(resolve(themes, 'theme-colors.less'), hdr('Theme colors as CSS custom properties (one compile, runtime html.dark switch).') + colorBlock(L, ':root') + '\n' + colorBlock(D, 'html.dark'))

// theme.less : the bridge (compile-time @x -> var(--x)) + the non-color base vars
// from dark.less (e.g. @imagedir, used in @{} interpolation -> must stay LESS) +
// the rest of the theme (common.less: mixins, breakpoints, media).
const nonColorBase = baseVars.filter(v => !isCss(v))
const bridge = hdr('BRIDGE: maps LESS @color_x to var(--color_x) so source compiles to CSS vars once.')
  + colorVars.map(v => `@${v}: var(--${v});`).join('\n') + '\n'
  + variants.map(([v, fn, n]) => `@${v}_${fn}${n}: var(--${v}_${fn}${n});`).join('\n') + '\n\n'
  + (nonColorBase.length ? `// non-color base vars (kept literal — used in @{} interpolation)\n${nonColorBase.map(v => `@${v}: ${L[v]};`).join('\n')}\n\n` : '')
  + '@import "themes/common.less";\n'
writeFileSync(resolve(themes, 'theme.less'), bridge)

writeFileSync(resolve(libAbs, 'theme-color-vars.json'), JSON.stringify({ colors: colorVars, variants }))
process.stdout.write(`theme-colors.less + theme.less (pont) : ${colorVars.length} couleurs + ${variants.length} variantes\n`)
